### ISSUE TITLE
Ограничить количество сообщений в сторе (до последних 100)

### ISSUE THREAD

**Issue by kana-sama** [kana-sama/donos#11]
Сейчас они хранятся все и рано или поздно мы охуеем

**Comment by zkbpkp** [comment]
Ну 100 это совсем мало, пару-тройку тысяч ок думаю.

**Comment by kana-sama** [comment]
Ну я уже храню только за последние сутки

**Comment by kana-sama** [comment]
https://github.com/kana-sama/donos/commit/b89af6053b982a901f1038883dd9c0951c957088
