### ISSUE TITLE
Команды /anon и /deanon

### ISSUE THREAD

**Issue by zkbpkp** [kana-sama/donos#36]
1. Команда `/deanon` которой можно ответить на **своё** сообщение и бот в истории пометит тебя как автора.

2. Команда `/anon` которой можно ответить на задеаноненное сообщение и бот снова скроет автора.

Ещё как вариант: `/deanonsession` заменяющее никнейм во всех сообщениях данной сессии на юзернейм автора.

**Comment by zkbpkp** [comment]
Вообще на счёт `/deanon` тут два варианта:
- `🚆 Визинг` превращается в `🚆 Визинг (@pidor)`
- `🚆 Визинг` превращается в `@pidor`

**Comment by zkbpkp** [comment]
То есть во втором случае если видишь историю впервые после деанона то не знаешь что остальные сообщения сессии принадлежат тому же человеку

**Comment by zkbpkp** [comment]
Вообще да думаю имеет смысл сделать `/deanon` которая будет полностью заменять никнейм (второй вариант из описанных выше) и постфактум нельзя будет узнать какой сессии принадлежало это сообщение; и `/deanonsession` где заменить никнейм во всех сообщениях сессии.

**Comment by zkbpkp** [comment]
Для `/deanonsession` я бы сделал ещё какое-нибудь подтверждение по типу "вы уверены?" чтобы случайно не ткнуть и не задеанонить всё

**Comment by kana-sama** [comment]
@KolesnichenkoDS 

Такс, опять же, есть мысль, что глобальный /deanon не нужен
Я попросту не храню айди всех сообщений, только за последние сутки. Я и текст сообщений не храню.

Самодеанон нужен для чего - чтобы показать в неком диалоге что ты тот кто ты есть, при этом не просто показать, а доказать, то есть система должна тебя выдать. Сделать это достаточно один раз, если человек не читал переписку то и знать ему не нужен.

То есть я считаю самой лучший реализацией деаона команду /deanon без аргументов и реплаев, которая просто раздаст всем юзерам системное сообщение, что `🚆 Визинг - @pidor`, то есть деанон только этой сессии и только один раз отдельным сообщением

**Comment by kana-sama** [comment]
В моем варианте это очень простая фича для реализации. Довольно интересная, потому что у юзера может не быть ника

**Comment by dmi-kov** [comment]
было бы норм, если после команды `/deanon`, когда все увидели кто это на самом деле - сменить всем участникам имена. Ну то есть это должна быть довольно дорогая фича для участников, чтоб постоянно юзать.

**Comment by kana-sama** [comment]
Ну /deanon же будет деанонить только себя, не считаю что это должно быть дорого, это как написать "я - кана", только с гарантией от бота

**Comment by kana-sama** [comment]
https://github.com/kana-sama/donos/commit/778d44f78f93aef41eac5b74388cd9e9eec18b53
