### ISSUE TITLE
История сообщений чата

### ISSUE THREAD

**Issue by zkbpkp** [kana-sama/donos#38]
Два варианта:

1. Форвардить все сообщения в канал
2. Ещё один бот, который будет пересылать сообщения либо постоянно, либо по требованию (за какой-то период)

Преимущество первого варианта очевидно в простоте реализации. Преимущество второго варианта в том что если реализовывать систему банов (#37) она позволит запретить читать сообщения забаненным пользователям.

**Comment by kana-sama** [comment]
Имплементировал первый вариант:
https://github.com/kana-sama/donos/commit/7524e30fe2dbb51fe1ce32c6c6d238db58d36fe4

Ишью оставлю открытым, потому что нужно еще обдумать второй вариант

**Comment by kana-sama** [comment]
Закрою, потому что все же считаю, что бан (не мьют) не нужен, фича реализована
